USE [master]
GO

/****** Object:  Database [SportGoods]    Script Date: 20.11.2022 14:48:08 ******/
CREATE DATABASE [SportGoods]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Base1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL\MSSQL\DATA\Base2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Base1_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQL\MSSQL\DATA\Base2_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SportGoods].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SportGoods] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SportGoods] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SportGoods] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SportGoods] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SportGoods] SET ARITHABORT OFF 
GO

ALTER DATABASE [SportGoods] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SportGoods] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SportGoods] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SportGoods] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SportGoods] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SportGoods] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SportGoods] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SportGoods] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SportGoods] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SportGoods] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SportGoods] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SportGoods] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SportGoods] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SportGoods] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SportGoods] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SportGoods] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SportGoods] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SportGoods] SET RECOVERY FULL 
GO

ALTER DATABASE [SportGoods] SET  MULTI_USER 
GO

ALTER DATABASE [SportGoods] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SportGoods] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SportGoods] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SportGoods] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SportGoods] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SportGoods] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SportGoods] SET  READ_WRITE 
GO


